apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-controller
  namespace: flux-system
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: HTTPS_PROXY
          value: http://172.16.71.74:8080
        - name: HTTP_PROXY
          value: http://172.16.71.74:8080
        - name: NO_PROXY
          value: localhost,127.0.0.1,10.96.0.1,10.96.0.0/12,.svc,.cluster.local,kubernetes.default.svc
